name: internal
description: A Flutter-based University Notice Board application
version: 1.0.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  sqflite_common_ffi_web: ^0.4.0+1
  path_provider: ^2.0.11
  file_picker: ^5.2.10
  sqflite_common_ffi: ^2.3.2+1
  open_file: ^3.2.1
  share_plus: ^7.2.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
